### ISSUE TITLE
CalledProcessError: returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Celine-Serry** [Darisia/SASCRiP#1]
Hi, 

I have a problem using SASCRiP. I first wanted to make my own index and t2g file running this code: 

`sascrip_functions.kallisto_bustools_count(
list_of_fastqs = 'E:/SASCRiP', # list of all the input FASTQ files in the required order
input_directory = True,
read_separator = ["R1", "R2"],
single_cell_technology = '10xv3', # type of single-cell tech used to generate the data
output_directory_path = 'E:/SASCRiP/output', # path where all output files will be saved
species_index = None, # path to the kallisto index for the species of interest
generate_index = True, #this will generate an index
species_fasta = 'E:/SASCRiP/Homo_sapiens.GRCh38.cdna.all.fa', #path to cdna fasta file for the index
species_t2g = None, # path to the transcripts-to-genes mapping file for the species of interest
species_gtf = "E:/SASCRiP/Homo_sapiens.GRCh38.108.gtf" #path to gtf file for making the t2g 
)`

But unfortunately it returned this error: 

Traceback (most recent call last):

  Cell In[12], line 1
    sascrip_functions.kallisto_bustools_count(

  File ~\anaconda3\Lib\site-packages\SASCRiP\sascrip_functions.py:598 in kallisto_bustools_count
    count.bustools_sort(output_busfile, sorted_busfile, threads=8, memory=memory)

  File ~\anaconda3\Lib\site-packages\kb_python\count.py:94 in bustools_sort
    run_executable(command)

  File ~\anaconda3\Lib\site-packages\kb_python\utils.py:114 in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))

CalledProcessError: Command 'C:\Users\Celin\anaconda3\Lib\site-packages\kb_python\bins\windows\bustools\bustools.exe sort -o E:/SASCRiP/output\Count_analysis\sorted.bus -T tmp -t 8 -m 4G E:/SASCRiP/output\Count_analysis\output.bus' returned non-zero exit status 3221225477.

I then tried to run the function with my already existing index and t2g file running this code:

`sascrip_functions.kallisto_bustools_count(
list_of_fastqs = r'E:\SASCRiP', # list of all the input FASTQ files in the required order
input_directory = True,
read_separator = ["R1", "R2"],
single_cell_technology = '10xv3', # type of single-cell tech used to generate the data
output_directory_path = r'E:\SASCRiP\output', # path where all output files will be saved
species_index = r'E:\SASCRiP\Homo_sapiens.GRCh38.cdna.all.index', # path to the kallisto index for the species of interest
species_t2g = r'E:\SASCRiP\t2g.txt' # path to the transcripts-to-genes mapping file for the species of interest
)`

But then I got this error:

Traceback (most recent call last):

  Cell In[14], line 1
    sascrip_functions.kallisto_bustools_count(

  File ~\anaconda3\Lib\site-packages\SASCRiP\sascrip_functions.py:595 in kallisto_bustools_count
    count.kallisto_bus(list_of_fastqs, species_index, single_cell_technology, all_count_out_path, threads=8)

  File ~\anaconda3\Lib\site-packages\kb_python\count.py:62 in kallisto_bus
    run_executable(command)

  File ~\anaconda3\Lib\site-packages\kb_python\utils.py:114 in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))

CalledProcessError: Command 'C:\Users\Celin\anaconda3\Lib\site-packages\kb_python\bins\windows\kallisto\kallisto.exe bus -i E:\SASCRiP\Homo_sapiens.GRCh38.cdna.all.index -o E:\SASCRiP\output\Count_analysis -x 10xv3 -t 8 E:\SASCRiP\pbmc_1k_v3_S1_mergedLanes_R1.fastq.gz E:\SASCRiP\pbmc_1k_v3_S1_mergedLanes_R2.fastq.gz' returned non-zero exit status 1.

**Do you maybe know what i can do to solve this?** 

I am running this code on a Windows11. I installed anaconda (python 3.11.5), and work through the Spyder IDE (5.4.3). I am using SASCRiP version 1.0.2, and installed this through ` pip install SASCRiP`.

**Comment by Darisia** [comment]
Hi Celine

The SASCRiP package has a new update. Maybe try downloading version 2. However, it sometimes has issues when running on windows. What you can try and adjust is the -m parameter and set it to 2G.

It’s not yet properly adjusted for windows so I’m not sure if this will fix the issue but it’s worth a try


On 14 Feb 2024, at 10:05, Celine ***@***.***> wrote:

﻿

Hi,

I have a problem using SASCRiP. I first wanted to make my own index and t2g file running this code:

sascrip_functions.kallisto_bustools_count( list_of_fastqs = 'E:/SASCRiP', # list of all the input FASTQ files in the required order input_directory = True, read_separator = ["R1", "R2"], single_cell_technology = '10xv3', # type of single-cell tech used to generate the data output_directory_path = 'E:/SASCRiP/output', # path where all output files will be saved species_index = None, # path to the kallisto index for the species of interest generate_index = True, #this will generate an index species_fasta = 'E:/SASCRiP/Homo_sapiens.GRCh38.cdna.all.fa', #path to cdna fasta file for the index species_t2g = None, # path to the transcripts-to-genes mapping file for the species of interest species_gtf = "E:/SASCRiP/Homo_sapiens.GRCh38.108.gtf" #path to gtf file for making the t2g )

But unfortunately it returned this error:

Traceback (most recent call last):

Cell In[12], line 1
sascrip_functions.kallisto_bustools_count(

File ~\anaconda3\Lib\site-packages\SASCRiP\sascrip_functions.py:598 in kallisto_bustools_count
count.bustools_sort(output_busfile, sorted_busfile, threads=8, memory=memory)

File ~\anaconda3\Lib\site-packages\kb_python\count.py:94 in bustools_sort
run_executable(command)

File ~\anaconda3\Lib\site-packages\kb_python\utils.py:114 in run_executable
raise sp.CalledProcessError(p.returncode, ' '.join(command))

CalledProcessError: Command 'C:\Users\Celin\anaconda3\Lib\site-packages\kb_python\bins\windows\bustools\bustools.exe sort -o E:/SASCRiP/output\Count_analysis\sorted.bus -T tmp -t 8 -m 4G E:/SASCRiP/output\Count_analysis\output.bus' returned non-zero exit status 3221225477.

I then tried to run the function with my already existing index and t2g file running this code:

sascrip_functions.kallisto_bustools_count( list_of_fastqs = r'E:\SASCRiP', # list of all the input FASTQ files in the required order input_directory = True, read_separator = ["R1", "R2"], single_cell_technology = '10xv3', # type of single-cell tech used to generate the data output_directory_path = r'E:\SASCRiP\output', # path where all output files will be saved species_index = r'E:\SASCRiP\Homo_sapiens.GRCh38.cdna.all.index', # path to the kallisto index for the species of interest species_t2g = r'E:\SASCRiP\t2g.txt' # path to the transcripts-to-genes mapping file for the species of interest )

But then I got this error:

Traceback (most recent call last):

Cell In[14], line 1
sascrip_functions.kallisto_bustools_count(

File ~\anaconda3\Lib\site-packages\SASCRiP\sascrip_functions.py:595 in kallisto_bustools_count
count.kallisto_bus(list_of_fastqs, species_index, single_cell_technology, all_count_out_path, threads=8)

File ~\anaconda3\Lib\site-packages\kb_python\count.py:62 in kallisto_bus
run_executable(command)

File ~\anaconda3\Lib\site-packages\kb_python\utils.py:114 in run_executable
raise sp.CalledProcessError(p.returncode, ' '.join(command))

CalledProcessError: Command 'C:\Users\Celin\anaconda3\Lib\site-packages\kb_python\bins\windows\kallisto\kallisto.exe bus -i E:\SASCRiP\Homo_sapiens.GRCh38.cdna.all.index -o E:\SASCRiP\output\Count_analysis -x 10xv3 -t 8 E:\SASCRiP\pbmc_1k_v3_S1_mergedLanes_R1.fastq.gz E:\SASCRiP\pbmc_1k_v3_S1_mergedLanes_R2.fastq.gz' returned non-zero exit status 1.

Do you maybe know what i can do to solve this?

I am running this code on a Windows11. I installed anaconda (python 3.11.5), and work through the Spyder IDE (5.4.3). I am using SASCRiP version 1.0.2, and installed this through pip install SASCRiP.

**Comment by Celine-Serry** [comment]
Hi, unfortunately updating does not work:
` pip install --upgrade sascrip==2.0` 
Note: you may need to restart the kernel to use updated packages.
ERROR: Could not find a version that satisfies the requirement sascrip==2.0 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.2.0, 0.2.1, 1.0.1, 1.0.2)
ERROR: No matching distribution found for sascrip==2.0

Or should I take 0.2.0 / 0.2.1?

When I use version 1.0.2 and set memory to '2G', then I get this: 

`sascrip_functions.kallisto_bustools_count(
list_of_fastqs = 'E:/SASCRiP', # list of all the input FASTQ files in the required order
input_directory = True,
read_separator = ["R1", "R2"],
single_cell_technology = '10xv3', # type of single-cell tech used to generate the data
output_directory_path = 'E:/SASCRiP/output', # path where all output files will be saved
species_index = None, # path to the kallisto index for the species of interest
generate_index = True, #this will generate an index
species_fasta = 'E:/SASCRiP/Homo_sapiens.GRCh38.cdna.all.fa', #path to cdna fasta file for the index
species_t2g = None, # path to the transcripts-to-genes mapping file for the species of interest
species_gtf = "E:/SASCRiP/Homo_sapiens.GRCh38.108.gtf", #path to gtf file for making the t2g 
memory = '2G'
)`

Traceback (most recent call last):

  Cell In[11], line 1
    sascrip_functions.kallisto_bustools_count(

  File ~\anaconda3\Lib\site-packages\SASCRiP\sascrip_functions.py:622 in kallisto_bustools_count
    filter_busfile(sorted_corrected_busfile, species_t2g, ecmap, transcripts, all_count_out_path, memory=memory)

  File ~\anaconda3\Lib\site-packages\SASCRiP\sascrip_functions.py:304 in filter_busfile
    count.bustools_count(captured_busfile, filtered_count_folder_files, species_t2g, ecmap_path, transcripts_path)

  File ~\anaconda3\Lib\site-packages\kb_python\count.py:178 in bustools_count
    run_executable(command)

  File ~\anaconda3\Lib\site-packages\kb_python\utils.py:114 in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))

CalledProcessError: Command 'C:\Users\Celin\anaconda3\Lib\site-packages\kb_python\bins\windows\bustools\bustools.exe count -o E:/SASCRiP/output\Count_analysis\filtered_counts -g E:/SASCRiP/output\transcripts_to_genes.txt -e E:/SASCRiP/output\Count_analysis\matrix.ec -t E:/SASCRiP/output\Count_analysis\transcripts.txt --genecounts E:/SASCRiP/output\Count_analysis\captured_barcode.bus' returned non-zero exit status 3221225477.


when I try it again with an already existing t2g and index file:

`sascrip_functions.kallisto_bustools_count(
list_of_fastqs = r'E:\SASCRiP', # list of all the input FASTQ files in the required order
input_directory = True,
read_separator = ["R1", "R2"],
single_cell_technology = '10xv3', # type of single-cell tech used to generate the data
output_directory_path = r'E:\SASCRiP\output', # path where all output files will be saved
species_index = r'E:\SASCRiP\Homo_sapiens.GRCh38.cdna.all.index', # path to the kallisto index for the species of interest
species_t2g = r'E:\SASCRiP\t2g.txt', # path to the transcripts-to-genes mapping file for the species of interest
memory = '2G')`

Traceback (most recent call last):

  Cell In[12], line 1
    sascrip_functions.kallisto_bustools_count(

  File ~\anaconda3\Lib\site-packages\SASCRiP\sascrip_functions.py:595 in kallisto_bustools_count
    count.kallisto_bus(list_of_fastqs, species_index, single_cell_technology, all_count_out_path, threads=8)

  File ~\anaconda3\Lib\site-packages\kb_python\count.py:62 in kallisto_bus
    run_executable(command)

  File ~\anaconda3\Lib\site-packages\kb_python\utils.py:114 in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))

CalledProcessError: Command 'C:\Users\Celin\anaconda3\Lib\site-packages\kb_python\bins\windows\kallisto\kallisto.exe bus -i E:\SASCRiP\Homo_sapiens.GRCh38.cdna.all.index -o E:\SASCRiP\output\Count_analysis -x 10xv3 -t 8 E:\SASCRiP\pbmc_1k_v3_S1_mergedLanes_R1.fastq.gz E:\SASCRiP\pbmc_1k_v3_S1_mergedLanes_R2.fastq.gz' returned non-zero exit status 1.

**Comment by Darisia** [comment]
Sorry, you are using the updated package - another update is coming but will only be available at the end of the week. 
In the meantime, the one you are using should work for what you want to do but there may be a memory issue. What you can try is pasting the actual execution code into your command prompt and try running it. The place it is getting stuck is at the count step - which is the last step. I have also noticed on windows that it would get stuck at the filtering step as well. 

The code you would paste into the command prompt is: 
```C:\Users\Celin\anaconda3\Lib\site-packages\kb_python\bins\windows\bustools\bustools.exe count -o E:/SASCRiP/output\Count_analysis\filtered_counts -g E:/SASCRiP/output\transcripts_to_genes.txt -e E:/SASCRiP/output\Count_analysis\matrix.ec -t E:/SASCRiP/output\Count_analysis\transcripts.txt --genecounts E:/SASCRiP/output\Count_analysis\captured_barcode.bus``` - this may help you figure out the problem as well

The second time you tried to run it with an existing index isn't even getting past the first step which suggests that there may be an issue with the index. Is it a kallisto index? 

Finally, the next step in the workflow that converts the matrix into a seurat-compatible matrix will require you have a t2g file that has no missing data. It has a bug that is being fixed as we speak and won't be an issue in the new update. But for now it will not produce correct output if the transcripts to genes file has missing data. Also, the next step would require you work in a Unix environment, unfortunately.

**Comment by Darisia** [comment]
Sorry just one more thing

I know that you get an error - but there should be output generated from the other parts of the functions that has successfully run - do you see the output in your main output directory?

**Comment by Celine-Serry** [comment]
Oh I see it indeed created some output: the index, the t2g and the count_analysis folder with the filtered and unfiltered counts and the files with the meta-data... any idea whats going on?

**Comment by Celine-Serry** [comment]
Ah I see, I will wait for the update and see what will happen. Since its stuck only at the last step, can I still use the data? The existing index was indeed a kallisto index (created via Ubuntu). When I open the t2g file created by SASCRiP I indeed see some gene IDs that don't have a gene in that column. Can I simply remove these rows from the t2g file? 

![image](https://github.com/Darisia/SASCRiP/assets/127406679/4404ddd9-86b4-49f5-a029-5be10f072a4f)

**Comment by Darisia** [comment]
So if there is the relevant files in the 'unfiltered counts' folder. The relevant files being 'unfiltered_counts.barcodes.txt', 'unfiltered_counts.genes.txt', and 'unfiltered_counts.mtx' and didn't create the filtered version of these - the problem likely is with the filtering step which has been an issue on windows before and I haven't been able to solve this problem. However, you can still work with the unfiltered counts - you just need to keep in mind that when visualising - all of the barcodes will be there even if they detected 0 transcripts (those would have been filtered during the filtering step)

**Comment by Darisia** [comment]
With reference to the t2g file - it wouldn't be entirely accurate to simply remove the missing data columns. It would be better to try and replace the empty spaces with the ENSG gene ID instead of leaving it blank or removing it. 

This has been an issue before - but will be fixed in the next update. This update will be released tomorrow so If you don't want to play around with editing the t2g file - hopefully by tomorrow you would be able to use it as is :)

However, if you would like to remove it so you could do a preliminary analysis - then I think it should be fine.

**Comment by Celine-Serry** [comment]
ah indeed, unfiltered counts worked, and contains those three files, and filtered counts is an empty folder. I can use these unfiltered counts files and import them into R to work with Seurat and filter the data there right? 

Ah amazing! Then I will just wait for the update :) Thank you!

**Comment by Darisia** [comment]
At the moment - Seurat won't be able to process the counts as is. This is the whole basis for the package - to convert the counts to a Seurat-compatible format. Which will require you to use the seurat_matrix function (this function is what needs to be updated 
 before you use it) - once you convert you will see three new zipped files that are created - those can be read into R for use with Seurat. However to run seurat_matrix - you will need to use a Linux OS. However, I am sure there may be another way to convert it if other people have also had the same problem

**Comment by Celine-Serry** [comment]
Ah I see. That saves me some time haha. Thanks!

**Comment by Darisia** [comment]
I will comment here as soon as the new update is posted so you can try all of the other SASCRiP functions :) 

Thank you for bringing the issues to me. I appreciate it and hope the improvements will help

**Comment by Celine-Serry** [comment]
Thanks alot for the quick response! helps me a great deal :)

**Comment by Darisia** [comment]
Hi

SASCRiP is updated - you can find v1.1.0 on PyPi
Currently - it's still not fully compatible with Windows OS. Linux is required for running the seurat_matrix function and all functions after that.

In the new minor update - all changes are related to `seurat_matrix`:
1) `seurat_matrix` can accommodate the transcripts to genes mapping file that contains missing HGNC symbols
2) The `seurat_matrix` function is less computationally intensive and 
3) `seurat_matrix` is much faster than it was before (it can run in **seconds** with small datasets compared to the 15 minute run-time prior to updating)

**Comment by Darisia** [comment]
Since we have solved the CalledProcessError that this issue was opened with, I am going to close it. If there are any other problems please open another issue.
